// Auto-generated by align_panda.py v3 (scipy.ndimage.label + dilation)
// 算法：找 panda 头内白色 face 区联通块，dilate 5px 合并被眼睛/嘴巴 split 的小白
// 比对手动 5-preset 不准的 faceOffset，给每个 panda 单独算更精准的 anchor
//
// 用法（在 materials.ts 末尾）：
//   import { PANDA_ALIGN_OVERRIDES } from './panda-align-overrides';
//   PANDA_HEADS.forEach(p => {
//     if (PANDA_ALIGN_OVERRIDES[p.id]) p.faceOffset = PANDA_ALIGN_OVERRIDES[p.id];
//   });

export const PANDA_ALIGN_OVERRIDES: Record<string, { x: number; y: number; w: number; h: number }> = {
  'panda-01': { x: 41, y: 53, w: 255, h: 179 },
  'panda-02': { x: 82, y: 68, w: 176, h: 175 },
  'panda-03': { x: 87, y: 61, w: 215, h: 167 },
  'panda-04': { x: 123, y: 78, w: 174, h: 165 },
  'panda-05': { x: 2, y: 16, w: 321, h: 222 },
  'panda-06': { x: 6, y: 5, w: 272, h: 239 },
  'panda-07': { x: 83, y: 0, w: 246, h: 243 },
  'panda-08': { x: 130, y: 16, w: 220, h: 213 },
  'panda-09': { x: 63, y: 77, w: 221, h: 165 },
  'panda-10': { x: 12, y: 85, w: 320, h: 152 },
  'panda-11': { x: 75, y: 5, w: 275, h: 239 },
  'panda-12': { x: 82, y: 68, w: 176, h: 175 },
  'panda-13': { x: 0, y: 25, w: 349, h: 210 },
  'panda-14': { x: 0, y: 11, w: 349, h: 229 },
  'panda-15': { x: 0, y: 36, w: 349, h: 195 },
  'panda-16': { x: 124, y: 109, w: 138, h: 127 },
  'panda-17': { x: 0, y: 25, w: 349, h: 209 },
  'panda-18': { x: 3, y: 0, w: 344, h: 244 },
  'panda-19': { x: 0, y: 26, w: 349, h: 207 },
  'panda-20': { x: 64, y: 71, w: 220, h: 173 },
  'panda-21': { x: 0, y: 3, w: 349, h: 228 },
  'panda-22': { x: 0, y: 20, w: 349, h: 216 },
  'panda-23': { x: 0, y: 2, w: 349, h: 241 },
  'panda-24': { x: 0, y: 14, w: 310, h: 225 },
  'panda-crossarm': { x: 6, y: 5, w: 272, h: 239 },
  'panda-hand': { x: 2, y: 16, w: 321, h: 222 },
  'panda-head': { x: 41, y: 53, w: 255, h: 179 },
  'panda-lean': { x: 87, y: 61, w: 215, h: 167 },
  'panda-lie': { x: 123, y: 78, w: 174, h: 165 },
  'panda-new-12-54-41': { x: 0, y: 25, w: 349, h: 210 },
  'panda-new-12-56-09': { x: 0, y: 11, w: 349, h: 229 },
  'panda-new-12-57-00': { x: 0, y: 36, w: 349, h: 195 },
  'panda-new-12-57-44': { x: 124, y: 109, w: 138, h: 127 },
  'panda-new-12-59-06': { x: 0, y: 25, w: 349, h: 209 },
  'panda-new-13-00-50': { x: 3, y: 0, w: 344, h: 244 },
  'panda-new-13-01-34': { x: 0, y: 26, w: 349, h: 207 },
  'panda-new-13-02-36': { x: 64, y: 71, w: 220, h: 173 },
  'panda-new-13-03-41': { x: 0, y: 3, w: 349, h: 228 },
  'panda-new-13-05-34': { x: 0, y: 20, w: 349, h: 216 },
  'panda-new-13-06-25': { x: 0, y: 2, w: 349, h: 241 },
  'panda-new-13-07-51': { x: 0, y: 14, w: 310, h: 225 },
  'panda-plane': { x: 83, y: 0, w: 246, h: 243 },
  'panda-question': { x: 130, y: 16, w: 220, h: 213 },
  'panda-railing': { x: 63, y: 77, w: 221, h: 165 },
  'panda-salute': { x: 12, y: 85, w: 320, h: 152 },
  'panda-side': { x: 75, y: 5, w: 275, h: 239 },
  'panda-stand': { x: 82, y: 68, w: 176, h: 175 },
};
